[target.x86_64-unknown-freebsd]
image = "x86_64-unknown-freebsd"
[target.x86_64-pc-windows-gnu]
image = "x86_64-pc-windows-gnu"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
